name: focuszen
description: "FocusFlow ile tanışın: Dijital dikkat dağıtıcılardan arınarak hedeflerinize odaklanmanızı sağlayan şık ve işlevsel bir zamanlayıcı uygulaması. Bu minimalist tasarım, \"ash gray\" detay"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.0
  provider: ^6.1.2
  go_router: ^16.2.0
  shared_preferences: ^2.0.0
  wakelock_plus: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/dreamflow_icon.jpg
  remove_alpha_ios: true
